"""initial schema

Revision ID: 14e41098003c
Revises: 
Create Date: 2026-04-12 21:00:06.728526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14e41098003c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generated_recipes_user_id_created_at'), table_name='generated_recipes')
    op.drop_index(op.f('ix_generated_recipes_user_id_fingerprint'), table_name='generated_recipes')
    op.drop_index(op.f('ix_generated_recipes_user_id_is_saved_saved_at'), table_name='generated_recipes')
    op.alter_column('recipes', 'nutrition',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('recipes', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('recipes', 'generated_recipe_id')
    op.drop_column('recipes', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('recipes', sa.Column('generated_recipe_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('recipes', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('recipes', 'nutrition',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_index(op.f('ix_generated_recipes_user_id_is_saved_saved_at'), 'generated_recipes', ['user_id', 'is_saved', 'saved_at'], unique=False)
    op.create_index(op.f('ix_generated_recipes_user_id_fingerprint'), 'generated_recipes', ['user_id', 'fingerprint'], unique=False)
    op.create_index(op.f('ix_generated_recipes_user_id_created_at'), 'generated_recipes', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###
