"""drop legacy recipes table

Revision ID: 67fd645820b1
Revises: 14e41098003c
Create Date: 2026-04-12 21:10:44.766151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '67fd645820b1'
down_revision: Union[str, Sequence[str], None] = '14e41098003c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recipes_id'), table_name='recipes')
    op.drop_index(op.f('ix_recipes_image_cache_key'), table_name='recipes')
    op.drop_table('recipes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ingredients', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('steps', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('nutrition', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('preferences', sa.TEXT(), server_default=sa.text("'[]'::text"), autoincrement=False, nullable=False),
    sa.Column('allergies', sa.TEXT(), server_default=sa.text("'[]'::text"), autoincrement=False, nullable=False),
    sa.Column('image_cache_key', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('image_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('image_prompt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('recipes_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('recipes_pkey'))
    )
    op.create_index(op.f('ix_recipes_image_cache_key'), 'recipes', ['image_cache_key'], unique=False)
    op.create_index(op.f('ix_recipes_id'), 'recipes', ['id'], unique=False)
    # ### end Alembic commands ###
